language: node_js
node_js:
  - "4.2"
  - "4.1"
  - "4.0"
  - "3"

before_script:
  - npm install -g gulp
  - npm install

script: 
  - gulp
  - gulp jscs
  - gulp lint
  - gulp unitTests
  - gulp integrationTests
  
after_success:

after_failure:

before_deploy:

deploy:
  provider: npm
  api_key:
  on:
    branch: master

after_deploy: