os:
  - linux
#  - osx
language: node_js
node_js:
  - '4.0'
#  - '4.1'
#  - '4.2'
#  - '4.3'
#  - '4.4'
#  - '5.0'

notifications:
  email:
    recipients:
      - chuna@msoe.edu
      - kuczynskij@msoe.edu
      - leonardj@msoe.edu
      - farrowc@msoe.edu
    on_success: change
    on_failure: change

before_script:
  - npm install -g npm3
  - npm install -g gulp
  - chmod +x afterSuccess.sh
script:
  - gulp
  - gulp jscs
  - gulp lint
  - gulp unitTests
  - gulp integrationTests
after_success:
  - ./afterSuccess.sh

after_failure: 

before_deploy: 

deploy:
  provider: npm
  email: kuczynskij@msoe
  api_key:
    secure: FIYifm7Ox/HTsWrGZ2210qGAUEv1pnOivyYwhN2iBaPpMSt+hTOt+LHsjyG3Q6Wm/xqLcfrAtBRANEfrRjjdTdr2vHelp3xVkpdIuFxaHe1Rcj/rzVUjn+GG/iq2kv5oLEVgJSW94ktrikc38sReBvEMU5iC/NOXt+inIHYoDMnCmg4NUf0GrtCnDHEnWQcBcgeYEd+8qZ12p4UqcAwv2ZlDsqRrOYl4BdUgGUhbSuybvq0c4cT4Pl1zWXVzyj5vBuIqQCXDde/dbj0prJM9jp21IhQIr7QsOTDv3mIwtSrGCmH3SHVLAuuNW8vZkgoTfDSzQtFxzYuwZ9DkIloqpRFipt2qFPQRaV1iuvrcAcEzf4O5ctURZuBjjtJ+VTFDRu/dm7D9i5RQBIq7rQlBzNdRP1pVEpiCNUfvrdZImbuOOHBkb1pVLWqzsiWXDhYdm8dW1wU2Q6s/JK3sp4xs1H+ksTwwitwSRisn52QEPvzHW3i6drmq0NT/W/VtVYTrfSWYsKAHms66XiMGb08odiVbCgoBDWAMNLYoIyPwIDGOBqkdHD6JN1SQI3otmAFW91D8P6LNz5qPvxKzg63sK1gUa4rOJKprXksYYc7bVWM8hDLsu0FBm9m2mS7UalNdGzofaEn060ppWIHZZvig77pQrc2TlBsfpszlbqSSqww=
  on:
    condition: $TRAVIS_BRANCH == "beta" || $TRAVIS_BRANCH == "patch" || $TRAVIS_BRANCH == "minor" || $TRAVIS_BRANCH == "major"
    tags: true
after_deploy: 
after_script: 
env:
  global:
    secure: c9QJm9JAmexykW4Yd34cqEME0Zs77baW1P3PSgZOwVa1LNSFC0vtKVoigYNoASj32tcUSiN6OdvstdhRKzwDFxxSo8HK5eN0yEYiapYpf6R9A+wAMHNOccFSqb00McjIRWZqG4lUi3vDBKs50REwxZxH8fPDXgSy+QCNhgNmKRCptzvR0HbIZGE+SMXJf6FpDBRrnw0marFQHKqzmUQ+MEYRGTlMgzF6CqAsUyFPcc35WecppQhWo8JOy/6gRWxz1BpOEsytCel+M/lCNvZ7/qAtoigPBrd6hRoKKpihYpwSdW1rel+b903KVk4C5GhXPiHhBpcVvOfd98zcGRY3iVK4MWcf4t47FMcjDXUFcgGrd6aCG28EKtO2KhkK0wS7ivHV7AXZOoezpc8hdA24WgzAh2Mz81vZgrUgXaY3GR99kIkINU0me/TWekFoEDCB/UIhfXtqW6rWK3NW6b8uudpLEpZUle9G0ShH92wL8Do9koJgFTsTModHsSmnHUNKIYEb4RCOgvtiDISDZnJMs2cVIxUzZn2J7xUHljqjyBaa9y/9yt0sDsDjT9ZOM+9mcDXIAi/dOv06ucxYZ4QvfMWr+FUQR6C1vrocI1d0s2o1CEqWJBtSGJ2Y6vANi6aqXWNa2NMIFLTGgG4Nbh7CHA+N6qUuIaORpIVifQaKh44=
